

STEAM_LOGIN_EMAIL_AUTH_NEXT_BUTTON_X, STEAM_LOGIN_EMAIL_AUTH_NEXT_BUTTON_Y = 982, 711

STEAM_ENTER_EMAIL_GUARD_CODE_X, STEAM_ENTER_EMAIL_GUARD_CODE_Y = 946, 419

STEAM_LOGIN_EMAIL_AUTH_FINISH_BUTTON_X, STEAM_LOGIN_EMAIL_AUTH_FINISH_BUTTON_Y = 1091, 709

STEAM_PROFILE_PRIVACY_PAGE_BLANK_X, STEAM_PROFILE_PRIVACY_PAGE_BLANK_Y = 1716, 619

STEAM_PROFILE_PRIVACY_INVENTORY_X, STEAM_PROFILE_PRIVACY_INVENTORY_Y = 895, 714

STEAM_PROFILE_PRIVACY_INVENTORY_DROP_DOWN_MENU_PUBLIC_X, STEAM_PROFILE_PRIVACY_INVENTORY_DROP_DOWN_MENU_PUBLIC_Y = 908, 744

STEAM_WHO_CAN_SEND_ME_TRADE_OFFER_X, STEAM_WHO_CAN_SEND_ME_TRADE_OFFER_Y = 795, 782


STEAM_CLIENT_X_1, STEAM_CLIENT_Y_1 = 12, 84
STEAM_CLIENT_X_2, STEAM_CLIENT_Y_2 = 57, 105

STEAM_LOGIN_EMAIL_AUTH_CONFIRM_X_1, STEAM_LOGIN_EMAIL_AUTH_CONFIRM_Y_1 = 797, 384
STEAM_LOGIN_EMAIL_AUTH_CONFIRM_X_2, STEAM_LOGIN_EMAIL_AUTH_CONFIRM_Y_2 = 849, 436


STEAM_LOGIN_EMAIL_AFTER_NEXT_X_1, STEAM_LOGIN_EMAIL_AFTER_NEXT_Y_1 = 796, 388
STEAM_LOGIN_EMAIL_AFTER_NEXT_X_2, STEAM_LOGIN_EMAIL_AFTER_NEXT_Y_2 = 854, 440


STEAM_LOGIN_EMAIL_AUTH_SUCCESS_X_1, STEAM_LOGIN_EMAIL_AUTH_SUCCESS_Y_1 = 783, 385
STEAM_LOGIN_EMAIL_AUTH_SUCCESS_X_2, STEAM_LOGIN_EMAIL_AUTH_SUCCESS_Y_2 = 846, 443

STEAM_PROFILE_PAGE_SETUP_WELCOME_PAGE_X_1, STEAM_PROFILE_PAGE_SETUP_WELCOME_PAGE_Y_1 = 1141, 377
STEAM_PROFILE_PAGE_SETUP_WELCOME_PAGE_X_2, STEAM_PROFILE_PAGE_SETUP_WELCOME_PAGE_Y_2 = 1280, 400

STEAM_PROFILE_PAGE_X_1, STEAM_PROFILE_PAGE_Y_1 = 518, 138
STEAM_PROFILE_PAGE_X_2, STEAM_PROFILE_PAGE_Y_2 = 620, 248

STEAM_PROFILE_SETTINGS_PAGE_X_1, STEAM_PROFILE_SETTINGS_PAGE_Y_1 = 503, 105
STEAM_PROFILE_SETTINGS_PAGE_X_2, STEAM_PROFILE_SETTINGS_PAGE_Y_2 = 548, 148

STEAM_PROFILE_INVENTORY_OPTION_X_1, STEAM_PROFILE_INVENTORY_OPTION_Y_1 = 1165, 540
STEAM_PROFILE_INVENTORY_OPTION_X_2, STEAM_PROFILE_INVENTORY_OPTION_Y_2 = 1182, 543

STEAM_CLIENT_INVENTORY_PAGE_CONFIRM_X_1, STEAM_CLIENT_INVENTORY_PAGE_CONFIRM_Y_1 = 1238, 209
STEAM_CLIENT_INVENTORY_PAGE_CONFIRM_X_2, STEAM_CLIENT_INVENTORY_PAGE_CONFIRM_Y_2 = 1323, 227

STEAM_PROFILE_TRADE_OFFER_WHO_CAN_SEND_X_1, STEAM_PROFILE_TRADE_OFFER_WHO_CAN_SEND_Y_1 = 1166, 568
STEAM_PROFILE_TRADE_OFFER_WHO_CAN_SEND_X_2, STEAM_PROFILE_TRADE_OFFER_WHO_CAN_SEND_Y_2 = 1377, 597

STEAM_WHO_CAN_SEND_ME_TRADE_OFFER_X_1, STEAM_WHO_CAN_SEND_ME_TRADE_OFFER_Y_1 = 514, 818
STEAM_WHO_CAN_SEND_ME_TRADE_OFFER_X_2, STEAM_WHO_CAN_SEND_ME_TRADE_OFFER_Y_2 = 636, 834

STEAM_PROFILE_PRIVACY_PAGE_INVENTORY_CHANGE_X_1, STEAM_PROFILE_PRIVACY_PAGE_INVENTORY_CHANGE_Y_1 = 837, 719
STEAM_PROFILE_PRIVACY_PAGE_INVENTORY_CHANGE_X_2, STEAM_PROFILE_PRIVACY_PAGE_INVENTORY_CHANGE_Y_2 = 891, 728
